# Generated by Django 3.1.1 on 2020-09-27 12:29

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('upcoming_move_sequence_number', models.IntegerField(default=1, verbose_name='Sequence Number of Next Move')),
                ('winner', models.CharField(blank=True, choices=[('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=100, null=True, verbose_name='Winner of Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('column', models.IntegerField(verbose_name='Column')),
                ('row', models.IntegerField(verbose_name='row')),
                ('player', models.CharField(choices=[('YELLOW', 'Yellow'), ('RED', 'Red')], max_length=100, verbose_name='Player of Move')),
                ('sequence_number', models.IntegerField(verbose_name='Sequence Number')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='c4.game', verbose_name='Game')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
