# Generated by Django 3.1.1 on 2020-09-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c4', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='winner',
            new_name='winner_color',
        ),
        migrations.RenameField(
            model_name='move',
            old_name='player',
            new_name='player_color',
        ),
    ]
